version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - viacep-mock
    networks:
      - app-network

  viacep-mock:
    image: "nginx:latest"
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
